name: Build Samples

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v5
        with:
          version: latest-upstream
          actions-cache-folder: 'emsdk-cache'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build with Emscripten
        run: |
          export EMSCRIPTEN=$(dirname $(which emcc))
          cd workspaces/
          python3 build-samples-web.py

      - name: Upload docs result
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: build/site

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
