name: Build Samples

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.61

      - name: Install dependencies
        run: |
          sudo apt-get install python3-setuptools
          pip3 install --upgrade pip
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt --upgrade; fi

      - name: Build with Emscripten
        run: |
          export EMSCRIPTEN=$(dirname $(which emcc))
          python3 build-samples-web.py

      - name: Upload docs result
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: build/site

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
          cname: samples.supernovaengine.org
